# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4deba3d51dc9ce5d451d0c5b46d05669e27c3581c204219deb65ba5f69f8c8bbd3ccfcd718ba331ce1c832e05dbd8b488e7fd6115105cc06b8205d0f470b611

test:
  secret_key_base: e33ee67d94e7d0cbc71096eb7ec40dc3bc2a5a380ea57502d26eff4f855a38c34cfa8fd9c82473d4f5bb08e35380f8df5a1de0940f06cc9d2569698264dc1f07

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
